from typing import Protocol

from PySide6.QtGui import QEnterEvent, QKeyEvent, QMouseEvent


class MouseListener(Protocol):
    def on_mouse_press(self, event: QMouseEvent) -> None: ...
    def on_mouse_move(self, event: QMouseEvent) -> None: ...
    def on_mouse_release(self, event: QMouseEvent) -> None: ...


class KeyboardListener(Protocol):
    def on_key_press(self, event: QKeyEvent) -> None: ...
    def on_key_release(self, event: QKeyEvent) -> None: ...


class HoverListener(Protocol):
    def on_mouse_enter(self, event: QEnterEvent) -> None: ...
    def on_mouse_leave(self, event: object) -> None: ...
